name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - ipycanvas
  - ipywidgets
  - numpy
  - pandas
  - matplotlib
  - plotly
  - seaborn
  - scikit-learn
  - imageio
  - requests
  - selenium
  - beautifulsoup4

  - pip
  - pip:
    - pyodide-http


