name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - ipycanvas
  - ipywidgets
  - numpy
  - pandas
  - matplotlib
  - plotly
  - scikit-learn
  - libarchive
  - jupyterlab_server
#  - pyodide-http
  - pip
  - pip:
    - pyodide-http
    - seaborn

